"""correcoes_regras_tabelas

Revision ID: 0f49b56cde18
Revises: task8_task9_pontos
Create Date: 2026-05-17 02:00:00.261206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f49b56cde18'
down_revision: Union[str, None] = 'task8_task9_pontos'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'descarte', 'usuario', ['usuario_id'], ['id'])
    op.alter_column('pontuacao', 'data_reg',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_constraint('qrcode_token_token_key', 'qrcode_token', type_='unique')
    op.drop_index('ix_qrcode_token_token', table_name='qrcode_token')
    op.create_index(op.f('ix_qrcode_token_token'), 'qrcode_token', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qrcode_token_token'), table_name='qrcode_token')
    op.create_index('ix_qrcode_token_token', 'qrcode_token', ['token'], unique=False)
    op.create_unique_constraint('qrcode_token_token_key', 'qrcode_token', ['token'])
    op.alter_column('pontuacao', 'data_reg',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'descarte', type_='foreignkey')
    # ### end Alembic commands ###
