"""criacao_inicial

Revision ID: 14521236db26
Revises: 
Create Date: 2026-05-12 15:55:16.258068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14521236db26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('descarte',
    sa.Column('id_descarte', sa.Integer(), nullable=False),
    sa.Column('data_desc', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('tipo_residuo', sa.String(length=50), nullable=True),
    sa.Column('observacao', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('quantidade_confirmada', sa.Float(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('usuario_lat', sa.Float(), nullable=True),
    sa.Column('usuario_long', sa.Float(), nullable=True),
    sa.Column('ponto_lat', sa.Float(), nullable=True),
    sa.Column('ponto_long', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id_descarte')
    )
    op.create_index(op.f('ix_descarte_id_descarte'), 'descarte', ['id_descarte'], unique=False)
    op.create_table('endereco',
    sa.Column('id_end', sa.Integer(), nullable=False),
    sa.Column('rua', sa.String(), nullable=True),
    sa.Column('bairro', sa.String(), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=True),
    sa.Column('cep', sa.String(), nullable=True),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_end')
    )
    op.create_index(op.f('ix_endereco_id_end'), 'endereco', ['id_end'], unique=False)
    op.create_table('estoque',
    sa.Column('id_estoque', sa.Integer(), nullable=False),
    sa.Column('tipo_residuo', sa.String(length=50), nullable=False),
    sa.Column('quantidade_total', sa.Float(), nullable=True),
    sa.Column('ultima_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id_estoque'),
    sa.UniqueConstraint('tipo_residuo')
    )
    op.create_index(op.f('ix_estoque_id_estoque'), 'estoque', ['id_estoque'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('senha_hash', sa.String(), nullable=True),
    sa.Column('pontuacao_total', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), server_default='usuario', nullable=False),
    sa.Column('endereco_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['endereco_id'], ['endereco.id_end'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_estoque_id_estoque'), table_name='estoque')
    op.drop_table('estoque')
    op.drop_index(op.f('ix_endereco_id_end'), table_name='endereco')
    op.drop_table('endereco')
    op.drop_index(op.f('ix_descarte_id_descarte'), table_name='descarte')
    op.drop_table('descarte')
    # ### end Alembic commands ###
