"""make_usuario_id_nullable

Revision ID: 24319d505859
Revises: 7963bb80ec24
Create Date: 2026-07-15 14:00:01.161090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24319d505859'
down_revision: Union[str, None] = '7963bb80ec24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solicitacao_ponto_coleta', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('solicitacao_ponto_coleta', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
