"""criacao_pontuacao

Revision ID: 60d9ec0c960e
Revises: 14521236db26
Create Date: 2026-05-12 16:29:13.910245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60d9ec0c960e'
down_revision: Union[str, None] = '14521236db26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pontuacao',
    sa.Column('id_pontuacao', sa.Integer(), nullable=False),
    sa.Column('pontos', sa.Integer(), nullable=False),
    sa.Column('data_reg', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id_pontuacao')
    )
    op.create_index(op.f('ix_pontuacao_id_pontuacao'), 'pontuacao', ['id_pontuacao'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pontuacao_id_pontuacao'), table_name='pontuacao')
    op.drop_table('pontuacao')
    # ### end Alembic commands ###
