"""Add agenda model

Revision ID: 7963bb80ec24
Revises: 9862ea7959be
Create Date: 2026-07-14 17:02:14.387987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7963bb80ec24'
down_revision: Union[str, None] = '9862ea7959be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ponto_coleta_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('turno_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ponto_coleta_id'], ['ponto_coleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agendas_id'), 'agendas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agendas_id'), table_name='agendas')
    op.drop_table('agendas')
    # ### end Alembic commands ###
