"""usuario_nao_nulo

Revision ID: 88fbe58e1df5
Revises: 0f49b56cde18
Create Date: 2026-05-17 02:53:55.944883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88fbe58e1df5'
down_revision: Union[str, None] = '0f49b56cde18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuario', 'telefone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuario', 'senha_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'senha_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuario', 'telefone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuario', 'nome',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
