"""horarios_disponibilidade_ponto

Revision ID: 910ca4b3facc
Revises: d9eaeed7d61a
Create Date: 2026-06-19 00:22:36.553364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '910ca4b3facc'
down_revision: Union[str, None] = 'd9eaeed7d61a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horarios_disponibilidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ponto_coleta_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('hora_abertura', sa.Time(), nullable=False),
    sa.Column('hora_fechamento', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['ponto_coleta_id'], ['ponto_coleta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horarios_disponibilidade_id'), 'horarios_disponibilidade', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_horarios_disponibilidade_id'), table_name='horarios_disponibilidade')
    op.drop_table('horarios_disponibilidade')
    # ### end Alembic commands ###
