"""notificacao

Revision ID: 95379fb8f429
Revises: admin_audit_log
Create Date: 2026-06-17 15:10:46.339019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95379fb8f429'
down_revision: Union[str, None] = 'admin_audit_log'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensagem', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ponto_coleta_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ponto_coleta_id'], ['ponto_coleta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacoes_id'), 'notificacoes', ['id'], unique=False)
    op.drop_index('ix_audit_log_action', table_name='audit_log')
    op.drop_index('ix_audit_log_admin_id', table_name='audit_log')
    op.drop_index('ix_audit_log_created_at', table_name='audit_log')
    op.drop_index('ix_audit_log_id', table_name='audit_log')
    op.drop_index('ix_audit_log_target_id', table_name='audit_log')
    op.drop_index('ix_audit_log_target_type', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('motivo', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['usuario.id'], name='audit_log_admin_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='audit_log_pkey')
    )
    op.create_index('ix_audit_log_target_type', 'audit_log', ['target_type'], unique=False)
    op.create_index('ix_audit_log_target_id', 'audit_log', ['target_id'], unique=False)
    op.create_index('ix_audit_log_id', 'audit_log', ['id'], unique=False)
    op.create_index('ix_audit_log_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_log_admin_id', 'audit_log', ['admin_id'], unique=False)
    op.create_index('ix_audit_log_action', 'audit_log', ['action'], unique=False)
    op.drop_index(op.f('ix_notificacoes_id'), table_name='notificacoes')
    op.drop_table('notificacoes')
    # ### end Alembic commands ###
