"""rf009_pontos_temporarios_data_final

Revision ID: d9eaeed7d61a
Revises: 95379fb8f429
Create Date: 2026-06-18 12:55:39.449845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9eaeed7d61a'
down_revision: Union[str, None] = '95379fb8f429'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ponto_coleta', sa.Column('data_final', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ponto_coleta', 'data_final')
    # ### end Alembic commands ###
